# -*- coding: utf-8 -*-
"""DAR_YOLOv5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OBNEx_yF5VTLxIq97CdA-SSYXLso_WTv

**INSTALLING DEPENDENCIES**
"""

!git clone https://github.com/ultralytics/yolov5

import torch
from matplotlib import pyplot as plt
import numpy as np
import cv2

"""LOADING YOLOv5 MODEL"""

model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

model

!cd yolov5 && python train.py --img 935 --batch 2 --epochs 50 --data dataset.yaml --weights yolov5s.pt --workers 2

!cd yolov5

